### ISSUE TITLE
panic after snapshot applied in state sync 

### ISSUE THREAD

**Issue by yihuang** [evmos/ethermint#1084]
__System info:__ [[cronos branch](https://github.com/crypto-org-chain/ethermint/tree/release/v0.10.x)]

__Steps to reproduce:__

report by boris.
1. do a state sync
2. immediately after applied snapshot, it panic for dereference nil pointer.

Quick update for rocksdb statesync. Tried twice with the above method today and both works properly.
However, the following error returned right after the snapshot applied in rocksdb:

```
7:27AM INF Verified ABCI app appHash="" height=2804000 module=statesync server=node
7:27AM INF Snapshot restored format=1 hash="" height=2804000 module=statesync server=node
7:27AM INF Starting BlockPool service impl=BlockPool module=blockchain server=node
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x184a838]

goroutine 69008 [running]:
github.com/tharsis/ethermint/x/feemarket/keeper.Keeper.CalculateBaseFee({{0x2d8faa8, 0x40000a4630}, {0x2d301a8, 0x400145ddd0}, {{0x2d8faa8, 0x40000a4630}, 0x400019a280, {0x2d301a8, 0x400145dd40}, {0x2d301f8, ...}, ...}}, ...)
	/build/8qldbsl73im0m2d6z245hjl1jwm1x11n-source/vendor/github.com/tharsis/ethermint/x/feemarket/keeper/eip1559.go:44 +0x2f8
github.com/tharsis/ethermint/x/feemarket/keeper.(*Keeper).BeginBlock(0x4540247468, {{0x2d67e88, 0x40001a0000}, {0x2d94a20, 0x4540234d00}, {{0xb, 0x0}, {0x453fa20b10, 0x12}, 0x2ac921, ...}, ...}, ...)
	/build/8qldbsl73im0m2d6z245hjl1jwm1x11n-source/vendor/github.com/tharsis/ethermint/x/feemarket/keeper/abci.go:14 +0x98
github.com/tharsis/ethermint/x/feemarket.AppModule.BeginBlock(...)
	/build/8qldbsl73im0m2d6z245hjl1jwm1x11n-source/vendor/github.com/tharsis/ethermint/x/feemarket/module.go:139
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(0x400106ce80, {{0x2d67e88, 0x40001a0000}, {0x2d94a20, 0x4540234d00}, {{0xb, 0x0}, {0x453fa20b10, 0x12}, 0x2ac921, ...}, ...}, ...)
	/build/8qldbsl73im0m2d6z245hjl1jwm1x11n-source/vendor/github.com/cosmos/cosmos-sdk/types/module/module.go:479 +0x1e8
github.com/crypto-org-chain/cronos/app.(*App).BeginBlocker(...)
	/build/8qldbsl73im0m2d6z245hjl1jwm1x11n-source/app/app.go:762
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(0x40006e0ea0, {{0x454020bc80, 0x20, 0x20}, {{0xb, 0x0}, {0x453fa20b10, 0x12}, 0x2ac921, {0x399458c2, ...}, ...}, ...})
	/build/8qldbsl73im0m2d6z245hjl1jwm1x11n-source/vendor/github.com/cosmos/cosmos-sdk/baseapp/abci.go:194 +0x858
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(0x4001437c20, {{0x454020bc80, 0x20, 0x20}, {{0xb, 0x0}, {0x453fa20b10, 0x12}, 0x2ac921, {0x399458c2, ...}, ...}, ...})
	/build/8qldbsl73im0m2d6z245hjl1jwm1x11n-source/vendor/github.com/tendermint/tendermint/abci/client/local_client.go:280 +0x114
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(0x4001497220, {{0x454020bc80, 0x20, 0x20}, {{0xb, 0x0}, {0x453fa20b10, 0x12}, 0x2ac921, {0x399458c2, ...}, ...}, ...})
	/build/8qldbsl73im0m2d6z245hjl1jwm1x11n-source/vendor/github.com/tendermint/tendermint/proxy/app_conn.go:81 +0x58
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x2d68d30, 0x40014cad80}, {0x2d7e940, 0x4001497220}, 0x44e33af860, {0x2d904b8, 0x4001496500}, 0x1)
	/build/8qldbsl73im0m2d6z245hjl1jwm1x11n-source/vendor/github.com/tendermint/tendermint/state/execution.go:307 +0x318
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0x40002393b0, {{{0xb, 0x0}, {0x1e42e0e, 0x7}}, {0x40014588a0, 0x12}, 0x1, 0x2ac920, {{0x40042a7380, ...}, ...}, ...}, ...)
	/build/8qldbsl73im0m2d6z245hjl1jwm1x11n-source/vendor/github.com/tendermint/tendermint/state/execution.go:140 +0x108
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0x4000053180, 0x1)
	/build/8qldbsl73im0m2d6z245hjl1jwm1x11n-source/vendor/github.com/tendermint/tendermint/blockchain/v0/reactor.go:398 +0x9e4
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).SwitchToFastSync
	/build/8qldbsl73im0m2d6z245hjl1jwm1x11n-source/vendor/github.com/tendermint/tendermint/blockchain/v0/reactor.go:125 +0xec
```
After restart of cronosd, it will continue to sync

__Expected behavior:__ state sync should just work

__Actual behavior:__ [What actually happened]

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by yihuang** [comment]
we'll investigate first.

**Comment by JayT106** [comment]
> After restart of cronosd, it will continue to sync

Do you mean after the panic happens, restart the cronosd, it can proceed with incoming blocks and then catch up the network? If yes, looks like the feemarket module didn't set up well when restoring the snapshot?

**Comment by yihuang** [comment]
> > After restart of cronosd, it will continue to sync
> 
> Do you mean after the panic happens, restart the cronosd, it can proceed with incoming blocks and then catch up the network? If yes, looks like the feemarket module didn't set up well when restoring the snapshot?

yes, possibly, from the stack trace, it panic at [this line](https://github.com/crypto-org-chain/ethermint/blob/release/v0.7.x/x/feemarket/keeper/eip1559.go#L39), the only chance is `consParams.Block` is nil.
