### ISSUE TITLE
panic when running `go get github.com/evmos/ethermint/x/feemarket`

### ISSUE THREAD

**Issue by technicallyty** [evmos/ethermint#1533]
__System info:__ [v0.20.0-rc3](https://github.com/evmos/ethermint/releases/tag/v0.20.0-rc3)

__Steps to reproduce:__

1. create fresh go module
2. `go get github.com/evmos/ethermint/x/feemarket`
3. see error

__Expected behavior:__ [What you expected to happen]
should not panic
__Actual behavior:__ [What actually happened]
panics!
__Additional info:__ [Include gist of relevant config, logs, etc.]
```go
go get github.com/evmos/ethermint/x/feemarket
panic: internal error: can't find reason for requirement on github.com/StackExchange/wmi@v0.0.0-20180116203802-5d049714c4a6

goroutine 1 [running]:
cmd/go/internal/modget.(*resolver).updateBuildList.func1({{0x140012e0b80?, 0x1400066b518?}, {0x140001bad20?, 0x1400063bfa0?}})
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/cmd/go/internal/modget/get.go:1760 +0xf8
cmd/go/internal/modget.(*resolver).updateBuildList(0x140000b2500, {0x10076a290, 0x140001a2000}, {0x0, 0x0, 0x0})
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/cmd/go/internal/modget/get.go:1765 +0x450
cmd/go/internal/modget.(*resolver).resolveQueries(0x140000b2500, {0x10076a290, 0x140001a2000}, {0x140001b4048, 0x1, 0x10074f640?})
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/cmd/go/internal/modget/get.go:1243 +0x180
cmd/go/internal/modget.runGet({0x10076a290, 0x140001a2000}, 0x140001be2e8?, {0x1400019e1a0, 0x1, 0x1})
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/cmd/go/internal/modget/get.go:314 +0x38c
main.invoke(0x100a5e2a0, {0x1400019e190, 0x2, 0x2})
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/cmd/go/main.go:225 +0x2f8
main.main()
        /opt/homebrew/Cellar/go/1.19.1/libexec/src/cmd/go/main.go:179 +0x7ac
```

**Comment by fedekunze** [comment]
This is the expected behavior, if you want to add the module you need to add ethermint only:

```
go get/install github.com/evmos/ethermint
```
