### ISSUE TITLE
Evm tx randomly timed out

### ISSUE THREAD

**Issue by VictorTrustyDev** [evmos/ethermint#1554]
__System info:__ 
- ethermint v0.20.0-rc4
- Ubuntu 22.04.1 LTS
- go 1.19.4
- typescript + web3 to deploy & execute contracts

__Steps to reproduce:__

1. Create local node freshly
2. Submit some evm tx

__Expected behavior:__ 
Tx should be executed

__Actual behavior:__
```log
web3 deploy smart contract 3-nft721.sol on evmos chain
err Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!
    at Object.TransactionError (.../escraw/scripts/integration/nodejs/node_modules/web3-core-helpers/lib/errors.js:87:21)
    at .../escraw/scripts/integration/nodejs/node_modules/web3-core-method/lib/index.js:419:49
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
}
```
```log
deploy smart contract WETH.sol on ethermint chain
err Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!
    at Object.TransactionError (.../ethermint/tests/escan/node_modules/web3-core-helpers/lib/errors.js:87:21)
    at .../ethermint/tests/escan/node_modules/web3-core-method/lib/index.js:419:49
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
}
```
```log
execute function registerCollect() of WETH.sol on ethermint chain
err Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!
    at Object.TransactionError (.../ethermint/tests/escan/node_modules/web3-core-helpers/lib/errors.js:87:21)
    at .../ethermint/tests/escan/node_modules/web3-core-method/lib/index.js:419:49
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
}
```
I'm building integration test for escan, I have script which creates ~40 txs (both cosmos and evm txs) on local evmos node

The scripts run gracefully multiple times with evmos v9.1.0

Now when I cherry-pick the tests into v10.0.0-rc2, I can not finish the script because it always *randomly* timed out in one of my evm txs.
(I didn't check the v10.0.0-rc1 yet)

The problem also happens with ethermintd local node and my integration test for ethermintd.
Balance of the wallet used to deploy contract didn't changed.
The only log of ethermintd node (log level = error):
```log
11:53PM ERR Failed to read request err="websocket: close 1006 (abnormal closure): unexpected EOF" module=rpc-server protocol=websocket remote={"IP":"127.0.0.1","Port":60980,"Zone":""} server=node
11:53PM ERR error while stopping connection error="already stopped" module=rpc-server protocol=websocket server=node
```
and it was printed multiple times.

This issue:
- 3/3 times happened when I run my own integration test for evmos node (18 evm txs, failed at 8th or 9th evm tx)
- 4/7 times happened when I run my own integration test for ethermintd node (4 evm txs in 2 batches, randomly failed at 1st or 2nd batch)

**Comment by fedekunze** [comment]
Thank you, could you provide more info about the transaction and contract you were interacting with to try to reproduce the issue?

**Comment by VictorTrustyDev** [comment]
@fedekunze 
Here https://github.com/evmos/ethermint/pull/1556/files

**Comment by VictorTrustyDev** [comment]
You can also do `git cherry-pick 4078792aebe7ead6f2cf5bdd8c94add3cdf9f9a3` to bring the script into other branches
```bash
git checkout v0.19.3
git cherry-pick 4078792aebe7ead6f2cf5bdd8c94add3cdf9f9a3
make install
// => Success 10/10

git checkout v0.20.0-rc2
git cherry-pick 4078792aebe7ead6f2cf5bdd8c94add3cdf9f9a3
make install
// => Success 10/10

git checkout v0.20.0-rc3
git cherry-pick 4078792aebe7ead6f2cf5bdd8c94add3cdf9f9a3
make install
// => Hang at the first attemps
```
So probably something wrong between rc2 and rc3

**Comment by GAtom22** [comment]
Hi @VictorTrustyDev, thanks for reporting this issue! I investigated and seems that after running a Tx in `ReCheck` mode, it is not running it on `ModeDeliver`. The cycle should be one of these 2:

```
runTx(ModeCheck) -> runTx(DeliverMode)
runTx(ModeCheck) -> runTx(ModeReCheck) -> runTx(DeliverMode)
```

If getting errors on the `runTx(ModeCheck)` or `runTx(ModeReCheck)` should return an error. But in this case there are no errors, and the `runTx(DeliverMode)` it's not triggered.

This basically means that the Tx never changes the state, so it does not exist on the chain. As result, the test gets a timeout error because they don't get any Tx receipt. 

I'm still trying to figure out why this is happening. I'll keep you updated

**Comment by VictorTrustyDev** [comment]
Hi @GAtom22, so, as I guess before ^ with clue, the problem might comes between rc2 and rc3 so I tried to build one by one every commit between 2 versions following [this list](https://github.com/evmos/ethermint/pull/1518/commits) and the txs start stucking from commit `feed84b09cdc46820faddbababf3f69ce881789a` of #1455

**Comment by GAtom22** [comment]
Hi @VictorTrustyDev, thanks for your comment! Indeed it is the `AnteHandler`s refactor what introduced the bug. Particularly the corresponding to the `EthGasConsumeDecorator`. On `ReCheckMode` the `gasWanted` is not updated and there's an error on tendermint that it is not bubbled up. The error comes from the `postCheck` function at the mempool logic:

- [v0/mempool](https://github.com/tendermint/tendermint/blob/014cdcf09844d48f6d30f3e520034b7edffd9670/mempool/v0/clist_mempool.go#L469-L480)
- [v1/mempool](https://github.com/tendermint/tendermint/blob/014cdcf09844d48f6d30f3e520034b7edffd9670/mempool/v1/mempool.go#L627-L641)

The error message is  `"gas wanted -1 is negative"`, but this error is only logged at debug level.

A solution is to set a new context with a `gasWanted = 0` on ReCheckMode. See [PR #1566](https://github.com/evmos/ethermint/pull/1566) as an example of this.

**Comment by VictorTrustyDev** [comment]
Thanks @GAtom22 for your detailed explanation
