### ISSUE TITLE
Calling String() on *MsgEthereumTx panics

### ISSUE THREAD

**Issue by danburck** [evmos/ethermint#646]
__Steps to reproduce:__

In the x/evm module, package `types`

1. create message `msg := NewTxContract(nil, 0, nil, 100000, nil, nil, nil, []byte("test"), nil)`
2. call String()  on the message

__Expected behavior:__  returns `string`

__Actual behavior:__  panics with following log:

```
--- FAIL: TestMsgsTestSuite (0.00s)
    --- FAIL: TestMsgsTestSuite/TestMsgEthereumTx_String (0.00s)
        /Users/danielburckhardt/code/tharsis/ethermint/x/evm/types/suite.go:63: test panicked: reflect.Value.Interface: cannot return value obtained from unexported field or method
            goroutine 123 [running]:
            runtime/debug.Stack()
            	/usr/local/Cellar/go/1.17.1/libexec/src/runtime/debug/stack.go:24 +0x65
            github.com/stretchr/testify/suite.failOnPanic(0xc0011df6c0)
            	/Users/danielburckhardt/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:63 +0x3e
            panic({0x50469a0, 0x56807a0})
            	/usr/local/Cellar/go/1.17.1/libexec/src/runtime/panic.go:1038 +0x215
            reflect.valueInterface({0x507a2e0, 0xc00122fd88, 0xa}, 0xaf)
            	/usr/local/Cellar/go/1.17.1/libexec/src/reflect/value.go:1362 +0xd9
            reflect.Value.Interface(...)
            	/usr/local/Cellar/go/1.17.1/libexec/src/reflect/value.go:1351
            github.com/gogo/protobuf/proto.(*TextMarshaler).writeAny(0x0, 0xc00124c8c0, {0x507a2e0, 0xc00122fd88, 0x56f1250}, 0xc000eb8c00)
            	/Users/danielburckhardt/go/pkg/mod/github.com/regen-network/protobuf@v1.3.3-alpha.regen.1/proto/text.go:615 +0xa38
            github.com/gogo/protobuf/proto.(*TextMarshaler).writeStruct(0x619cec4, 0xc00124c8c0, {0x51a62e0, 0xc00122fd40, 0x5098360})
            	/Users/danielburckhardt/go/pkg/mod/github.com/regen-network/protobuf@v1.3.3-alpha.regen.1/proto/text.go:453 +0x8cd
            github.com/gogo/protobuf/proto.(*TextMarshaler).writeAny(0x5048fde, 0xc00124c8c0, {0x5218940, 0xc001242930, 0x56f1250}, 0xc000eb8600)
            	/Users/danielburckhardt/go/pkg/mod/github.com/regen-network/protobuf@v1.3.3-alpha.regen.1/proto/text.go:606 +0x8c5
            github.com/gogo/protobuf/proto.(*TextMarshaler).writeStruct(0x619cec4, 0xc00124c8c0, {0x51cc7a0, 0xc001242930, 0x100000000000320})
            	/Users/danielburckhardt/go/pkg/mod/github.com/regen-network/protobuf@v1.3.3-alpha.regen.1/proto/text.go:453 +0x8cd
            github.com/gogo/protobuf/proto.(*TextMarshaler).Marshal(0x619cec4, {0x5696800, 0xc001242960}, {0x56b21a8, 0xc001242930})
            	/Users/danielburckhardt/go/pkg/mod/github.com/regen-network/protobuf@v1.3.3-alpha.regen.1/proto/text.go:896 +0x367
            github.com/gogo/protobuf/proto.(*TextMarshaler).Text(0xc001240788, {0x56b21a8, 0xc001242930})
            	/Users/danielburckhardt/go/pkg/mod/github.com/regen-network/protobuf@v1.3.3-alpha.regen.1/proto/text.go:908 +0x56
            github.com/gogo/protobuf/proto.CompactTextString(...)
            	/Users/danielburckhardt/go/pkg/mod/github.com/regen-network/protobuf@v1.3.3-alpha.regen.1/proto/text.go:930
            github.com/tharsis/ethermint/x/evm/types.(*MsgEthereumTx).String(...)
            	/Users/danielburckhardt/code/tharsis/ethermint/x/evm/types/tx.pb.go:50
            github.com/tharsis/ethermint/x/evm/types.(*MsgsTestSuite).TestMsgEthereumTx_String(0xc0011b7ec0)
            	/Users/danielburckhardt/code/tharsis/ethermint/x/evm/types/msg_test.go:190 +0xa5
            reflect.Value.call({0xc00120be00, 0xc0011d2e20, 0xa239352a}, {0x5245a97, 0x4}, {0xc001179e70, 0x1, 0xc001179d80})
            	/usr/local/Cellar/go/1.17.1/libexec/src/reflect/value.go:543 +0x814
            reflect.Value.Call({0xc00120be00, 0xc0011d2e20, 0xc0011b7ec0}, {0xc001179e70, 0x1, 0x1})
            	/usr/local/Cellar/go/1.17.1/libexec/src/reflect/value.go:339 +0xc5
            github.com/stretchr/testify/suite.Run.func1(0xc0011df6c0)
            	/Users/danielburckhardt/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:158 +0x4b6
            testing.tRunner(0xc0011df6c0, 0xc00014da70)
            	/usr/local/Cellar/go/1.17.1/libexec/src/testing/testing.go:1259 +0x102
            created by testing.(*T).Run
            	/usr/local/Cellar/go/1.17.1/libexec/src/testing/testing.go:1306 +0x35a
```

**Comment by fedekunze** [comment]
wondering if we should create a custom `String()` that casts the message to `*ethtypes.Transaction` and then calls `String` on that one

**Comment by twocs** [comment]
Is this the same issue?
https://github.com/gogo/protobuf/issues/693
